TIHLDE/Kvark

src/assets/css/index.css, src/components/inputs/Bool.tsx, src/components/story/StoryPopup.tsx, src/containers/Landing/components/Wave.tsx, src/containers/NewsDetails/components/NewsRenderer.tsx
=> feat(snow): remove snow on landing

CHANGELOG.md, src/api/api.tsx, src/api/hooks/News.tsx, src/api/hooks/Notification.tsx, src/api/hooks/User.tsx, src/containers/Profile/components/ProfileNotifications.tsx, src/containers/Profile/components/ProfilePaper.tsx, src/types/Types.tsx, src/utils.tsx
=> refactor(notifications): to pagination

CHANGELOG.md, package.json, src/URLS.tsx, src/api/api.tsx, src/api/hooks/ShortLink.tsx, src/components/navigation/Topbar.tsx, src/containers/ShortLinks/index.tsx, src/index.tsx, src/types/Types.tsx, yarn.lock
- Created a short-links page where members can create, view and delete their short-links.
- Uses the Web Share API for copying and sharing the url's
closes #4 
=> feat(short-links): create short-links page

src/components/navigation/Footer.tsx
Oppdatert til korrekt organisasjonsnummer
closes #35 
=> fix(OrgNr): Updated to correct org nr

src/containers/Http404/index.tsx
Swapped the 404 pictures for non logged in members and logged in members.
closes #32 
=> fix(404): changed pictures for members

src/components/miscellaneous/DetailContent.tsx, src/components/navigation/Navigation.tsx, src/components/navigation/Topbar.tsx, src/constant.tsx, src/containers/EventAdministration/components/EventEditor.tsx, src/containers/EventDetails/components/EventPriorities.tsx, src/containers/EventDetails/components/EventRenderer.tsx, src/containers/EventDetails/index.tsx, src/theme.tsx, src/utils.tsx
- Made the image smaller to be able to move info about events up on the page. This will hopefully allow os to fit more info on the page, such as Share-buttons/calendar-buttons/Host/participants/etc...
- New ui with single color on entire page, also the topbar. Quite different from the other pages. This required a new prop in the TopBar.
closes #16 
=> refactor(event): redesign

src/containers/EventDetails/components/EventRegistration.tsx
hot fix for registration i think this fixes it, and it stille works with a form, but im not 100% sure I think the bug comes from the return in the catch block and the catch block catching a undefined error on data.answers.forEach
closes #
=> fix(regestration): fixed bug where you could not register for an event

CHANGELOG.md, src/constant.tsx, src/containers/EventDetails/components/EventRegistration.tsx
=> Registration hotfix

CHANGELOG.md, src/api/hooks/User.tsx, src/containers/EventDetails/components/EventRenderer.tsx, src/containers/JobPostDetails/components/JobPostRenderer.tsx, src/containers/NewsDetails/components/NewsRenderer.tsx, src/containers/Pages/components/PagesAdmin.tsx, src/containers/Pages/specials/Index/index.tsx, src/containers/Profile/components/ProfileAdmin.tsx, src/containers/Profile/components/ProfilePaper.tsx, src/index.tsx, src/types/Enums.tsx, src/types/Types.tsx
=> feat(permissions): use new permissions system from backend

CHANGELOG.md, src/components/inputs/Upload.tsx
=> feat(upload): remove image from resource

src/api/api.tsx, src/api/hooks/User.tsx, src/containers/UserAdmin/components/PersonListItem.tsx
=> feat(users): implement new activate user endpoint

src/api/hooks/Group.tsx, src/api/hooks/Membership.tsx, src/api/hooks/User.tsx, src/api/hooks/Utils.tsx, src/assets/css/index.css, src/containers/GroupAdmin/components/AddMemberModal.tsx, src/containers/GroupAdmin/components/MemberListItem.tsx, src/containers/GroupAdmin/components/UpdateGroupModal.tsx, src/containers/GroupAdmin/index.tsx, src/containers/GroupOverview/components/GroupItem.tsx, src/containers/GroupOverview/index.tsx, src/containers/Pages/specials/Index/MembersCard.tsx, src/containers/UserAdmin/components/PersonListItem.tsx, src/theme.tsx, src/types/Enums.tsx, src/types/Types.tsx
- Changed some UI
- Stopped fetching of all users when the signed in user doesn't have access to do it
- Changed the ordering of groups
closes #78 
=> refactor(groups): dont fetch all users when not authed

package.json, src/components/layout/Banner.tsx, src/containers/GroupAdmin/index.tsx, src/types/global.d.ts, yarn.lock
=> feat(linkify): Update banner with linkify

CHANGELOG.md, src/api/api.tsx, src/api/hooks/Membership.tsx, src/components/layout/Pagination.tsx, src/containers/GroupAdmin/components/MemberListItem.tsx, src/containers/GroupAdmin/index.tsx, src/containers/Pages/specials/Index/MembersCard.tsx
Added pagination to listing of members of a group, and restyled the listing to add avatars
closes #
=> feat(membership) pagination and avatar

CHANGELOG.md, src/api/api.tsx, src/api/hooks/Pages.tsx, src/components/layout/Pagination.tsx, src/containers/Pages/components/PagesAdmin.tsx, src/containers/Pages/components/PagesList.tsx, src/containers/Pages/components/PagesSearch.tsx, src/containers/Pages/index.tsx, src/types/Types.tsx
=> feat(pages): add search

CHANGELOG.md, src/containers/Events/index.tsx, src/containers/JobPosts/index.tsx
=> feat(expired): show expired events and jobposts by switch

CHANGELOG.md, src/components/navigation/Sidebar.tsx
=> fix(sidebar): close sidebar on click inside pages

src/AppRoutes.tsx, src/URLS.tsx, src/api/hooks/Utils.tsx, src/components/layout/Banner.tsx, src/components/layout/Expand.tsx, src/components/layout/Tabs.tsx, src/components/navigation/Navigation.tsx, src/constant.tsx, src/containers/Cheatsheet/index.tsx, src/containers/Landing/components/EventsCalendarView.tsx, src/containers/Landing/components/NewStudentBox.tsx, src/containers/Landing/index.tsx, src/containers/NewStudent/index.tsx
Boksen vises nå mellom 20. juli og 15. september. Innloggede brukere kan trykke på "Ikke vis igjen" og da vil den skjules for dem.
closes #85 
=> feat(new-student): new page and landing box

src/api/hooks/Utils.tsx, src/components/inputs/Upload.tsx, src/components/miscellaneous/ShareButton.tsx, src/components/miscellaneous/ThemeSettings.tsx, src/components/navigation/BottomBar.tsx, src/components/navigation/Footer.tsx, src/components/navigation/ProfileTopbarButton.tsx, src/components/story/Story.tsx, src/containers/Cheatsheet/components/Files.tsx, src/containers/Companies/components/CompaniesForm.tsx, src/containers/EventDetails/components/EventRegistration.tsx, src/containers/EventDetails/components/EventRenderer.tsx, src/containers/Events/index.tsx, src/containers/ForgotPassword/index.tsx, src/containers/JobPostDetails/components/JobPostRenderer.tsx, src/containers/JobPosts/index.tsx, src/containers/Landing/components/EventsCalendarView.tsx, src/containers/Landing/components/EventsListView.tsx, src/containers/Landing/components/NewStudentBox.tsx, src/containers/Landing/components/NewsListView.tsx, src/containers/Landing/components/Wave.tsx, src/containers/LogIn/index.tsx, src/containers/NewStudent/index.tsx, src/containers/Pages/components/PagesSearch.tsx, src/containers/Profile/components/ProfileContent.tsx, src/containers/Profile/components/ProfileSettings.tsx, src/containers/Profile/index.tsx, src/containers/ShortLinks/index.tsx, src/containers/SignUp/index.tsx, src/index.tsx
Events legges til slik:
```
window.gtag('event', 'action', {
event_category: 'category',
event_label: 'Description/More info',
});
```
Der kategori for eks er 'video', action er 'play' og label er 'Kattevideo'. Har prøvd å holde meg så godt jeg kan til denne standarden.
Mangler event for "Meld på fadderuka"-knappen som kommer på forsiden med #122 , legges inn når den merges
closes #121 
=> feat(analytics): add google analytics events

CHANGELOG.md, src/URLS.tsx, src/components/layout/Banner.tsx, src/components/miscellaneous/ListItem.tsx, src/components/miscellaneous/MarkdownRenderer.tsx, src/components/navigation/BottomBar.tsx, src/components/navigation/Sidebar.tsx, src/components/story/Story.tsx, src/constant.tsx, src/containers/Landing/components/NewStudentBox.tsx, src/containers/Profile/components/ProfileContent.tsx, src/index.tsx
- Word-wrapping ios
- News listitem published at
- Bottom bar button spacing
- Story shadow ios
- New student join button
- Profile menu new ui
- New "New student" link
=> refactor(ui): fix multiple issues

CHANGELOG.md, src/api/api.tsx, src/api/hooks/User.tsx, src/components/layout/Paper.tsx, src/components/miscellaneous/Avatar.tsx, src/containers/EventAdministration/components/Participant.tsx, src/containers/UserAdmin/components/PersonListItem.tsx, src/theme.tsx
Lagt til mulighet til å slette "ventende" brukere og legge ved en begrunnelse. Har også lagt til visning av epost til "ventende" medlemmer. Også gjort litt forbedringer på props på diverse komponenter.
=> feat(users): decline users

src/AppRoutes.tsx, src/api/hooks/Utils.tsx, src/components/inputs/Upload.tsx, src/components/miscellaneous/ShareButton.tsx, src/components/miscellaneous/ThemeSettings.tsx, src/components/navigation/BottomBar.tsx, src/components/navigation/Footer.tsx, src/components/navigation/ProfileTopbarButton.tsx, src/components/story/Story.tsx, src/containers/Cheatsheet/components/Files.tsx, src/containers/Companies/components/CompaniesForm.tsx, src/containers/EventDetails/components/EventRegistration.tsx, src/containers/EventDetails/components/EventRenderer.tsx, src/containers/Events/index.tsx, src/containers/ForgotPassword/index.tsx, src/containers/JobPostDetails/components/JobPostRenderer.tsx, src/containers/JobPosts/index.tsx, src/containers/Landing/components/EventsCalendarView.tsx, src/containers/Landing/components/EventsListView.tsx, src/containers/Landing/components/NewStudentBox.tsx, src/containers/Landing/components/NewsListView.tsx, src/containers/Landing/components/Wave.tsx, src/containers/LogIn/index.tsx, src/containers/NewStudent/index.tsx, src/containers/Pages/components/PagesSearch.tsx, src/containers/Profile/components/ProfileContent.tsx, src/containers/Profile/components/ProfileSettings.tsx, src/containers/Profile/index.tsx, src/containers/ShortLinks/index.tsx, src/containers/SignUp/index.tsx
Add custom hook for Google Analytics in order to keep the implementation DRY and reusable.
closes #
=> refactor(google-analytics): reimplement analytics with hooks

CHANGELOG.md, src/containers/Profile/components/ProfileNotifications.tsx, src/types/Types.tsx
Changes:
Viser knapp for å åpne linker som nå kommer på enkelte varsler fra backend (tihlde/Lepton#171)
Screenshots:
=> feat(notifications): add description and link

CHANGELOG.md, src/components/layout/__tests__/Banner.spec.tsx, src/pages/UserAdmin/index.tsx
closes #129 
Changes: Lagt til alumnni i brukeradmin 
Screenshots:
=> feat(useradmin): added option for filtering alumni

CHANGELOG.md, src/components/forms/FormAnswers.tsx, src/components/forms/FormView.tsx, src/hooks/Form.tsx, src/pages/EventDetails/components/EventRegistration.tsx, src/pages/Events/index.tsx, src/pages/Form/index.tsx, src/pages/JobPosts/index.tsx
Det er ikke mulig å svare på evalueringsskjemaer uten spørsmål. Akkurat nå er det 50 stk som var på Cognite arrangement som ikke klarer å svare på et slikt og dermed ikke kan melde seg på andre arrangementer
=> hotfix(forms): evaluation answers

src/pages/Pages/specials/Index/ErrorCard.tsx
Endret link for rapportering av problemer til index
closes #141 
Changes:
Screenshots:
=> feat(Pages): Updated the GitHub link

src/components/miscellaneous/BadgeInput.tsx
closes #
Changes:
Screenshots:
=> refactor(CTF): changed the layout of the badgeinput component for CTFs

src/api/api.tsx, src/components/miscellaneous/NewsListItem.tsx
Nødvendig for https://github.com/TIHLDE/Lepton/pull/359
closes N/A
Changes:
Screenshots:
=> refactor(urls): update backend-urls to plural

CHANGELOG.md, src/api/api.tsx, src/hooks/Group.tsx, src/pages/Groups/fines/index.tsx, src/types/Group.tsx, src/types/index.tsx
closes https://github.com/TIHLDE/Lepton/issues/363
Changes:
- Lagt til statistikk for botsystemet. Brukere kan se antall betalt, antall godkjent og ikke betalt, samt antall ikke godkjent.
Screenshots:
=> feat(fines): add statistics

CHANGELOG.md, src/components/inputs/TextField.tsx, src/pages/Groups/fines/AddFineDialog.tsx, src/pages/Groups/laws/AddLawDialog.tsx, src/pages/Groups/laws/LawItem.tsx, src/pages/ShortLinks/index.tsx, src/types/Group.tsx, src/utils.tsx
closes #322 
Changes:
- Bedre sortering fra backend, lagt til nytt felt for å støtte dette.
- Fikset bug der beløp ikke ble endre i "Ny bot" ved endret lovbrudd
- Endret litt tekst
Screenshots:
=> refactor(laws): add separate paragraph field

CHANGELOG.md, src/api/api.tsx, src/components/miscellaneous/StrikeListItem.tsx, src/hooks/User.tsx, src/types/User.tsx
Følger opp https://github.com/TIHLDE/Lepton/pull/414
closes N/A
Changes:
Screenshots:
=> refactor(user): load permissions separately

CHANGELOG.md, src/api/api.tsx, src/components/miscellaneous/Avatar.tsx, src/components/miscellaneous/UserInformation.tsx, src/hooks/Event.tsx, src/hooks/User.tsx, src/pages/EventDetails/components/EventPublicRegistrationsList.tsx, src/pages/EventDetails/components/EventRenderer.tsx, src/pages/Profile/components/ProfileEvents.tsx, src/pages/Profile/components/ProfileSettings.tsx, src/pages/UserAdmin/components/PersonListItem.tsx, src/theme.tsx, src/types/Event.tsx, src/types/User.tsx
Avhenger av https://github.com/TIHLDE/Lepton/pull/413
closes #335 
Changes:
Alle innloggede brukere kan nå se hvem som er påmeldt arrangementer. Brukere kan reservere seg mot å bli oppført på deltagerlisten.
Screenshots:
=> feat(event): public event registrations

src/pages/UserAdmin/index.tsx
Admins kan se hvor mange medlemmer som vises i brukeradmin siden
closes #346
Changes: Viser antall medlemmer som vises på siden
Screenshots:
=> feat(admin): show members count

CHANGELOG.md, package.json, src/hooks/Confetti.tsx, src/pages/EventDetails/components/EventRegistration.tsx, src/pages/SignUp/index.tsx, yarn.lock
closes #353 
Changes:
Viser konfetti når person lager ny bruker og når en bruker melder seg på et arrangement.
Screenshots:
=> feat(confetti): on user signup and event registration

vite.config.ts
closes N/A
Changes:
- Håper dette kan hjelpe med å debugge feil i sentry
Screenshots:
=> chore: sourcemaps

CHANGELOG.md, src/pages/Form/index.tsx
closes #372 
Changes: Added confetti that appear when you submit a form 
Screenshots:
=> feat(Form): added confetti on submission

src/pages/EventDetails/components/EventPublicRegistrationsList.tsx
closes #
Changes: Fixed padding on the Event registration list 
Screenshots:
=> fix(event): padding in public registrations

CHANGELOG.md, src/URLS.tsx, src/pages/Groups/GroupDetails.tsx, src/pages/Groups/events/index.tsx
closes #319 
Changes:
Screenshots:
=> feat(group): events

CHANGELOG.md, src/components/forms/FormDetailsEditor.tsx, src/pages/EventAdministration/components/EventFormAdmin.tsx, src/types/Form.tsx
closes N/A
Changes:
- Hindret også at templates lastes inn før man expander <Expand />
Screenshots:
=> feat(forms): email on group form submission

CHANGELOG.md, src/pages/EventDetails/components/EventPublicRegistrationsList.tsx
closes #420 
Changes:
Screenshots:
=> refactor(events): disable click on anonymous users

CHANGELOG.md, src/components/navigation/Navigation.tsx, src/components/navigation/Sidebar.tsx, src/components/navigation/Topbar.tsx
closes N/A
Changes:
Lagt til link til fondet sin side på nettsiden
Lagt til generell støtte for eksterne linker i topbar
Screenshots:
=> feat(links): add fondet

CHANGELOG.md, src/api/api.tsx, src/hooks/Event.tsx, src/hooks/Form.tsx, src/pages/EventDetails/components/EventRenderer.tsx, src/pages/Events/index.tsx, src/types/Event.tsx
closes N/A
Changes:
Brukere kan markere arrangementer som favoritter og filterer på dem, samt motta varsel ved påmeldingsstart. Avhenger av https://github.com/TIHLDE/Lepton/pull/527
Screenshots:
=> feat(events): mark as favorite

CHANGELOG.md, src/AppRoutes.tsx, src/URLS.tsx, src/api/toddel.tsx, src/components/inputs/Upload.tsx, src/components/navigation/Navigation.tsx, src/hooks/Toddel.tsx, src/pages/Landing/components/EventsView.tsx, src/pages/Toddel/components/CreateToddelDialog.tsx, src/pages/Toddel/components/ToddelListItem.tsx, src/pages/Toddel/index.tsx, src/types/Enums.tsx, src/types/Toddel.tsx, src/types/index.tsx
Avhenger av https://github.com/TIHLDE/Lepton/pull/533
closes N/A
Changes:
- Töddel har nå sin egen siden på nettsiden.
- Redaksjonen, HS og Index kan legge til, redigere og slette publikasjoner.
Screenshots:
=> feat(töddel): add Töddel

CHANGELOG.md, src/pages/EventAdministration/components/EventEditor.tsx, src/pages/Groups/overview/index.tsx
closes N/A
Changes:
Screenshots:
=> feat(groups): edit board title

src/pages/EventDetails/components/EventRenderer.tsx, src/pages/Groups/about/MembersHistoryCard.tsx
fixed some bugs
closes #508 #509
Changes: fixed some bugs 
Screenshots:
=> fix(bugs): fixed #509 and #508

CHANGELOG.md, src/api/api.tsx, src/hooks/Group.tsx, src/pages/Groups/fines/AddFineDialog.tsx, src/pages/Groups/fines/FineItem.tsx, src/types/Group.tsx
closes #533 
closes #534 
Changes:
Screenshots:
=> feat: defend fines

src/pages/EventDetails/components/EventPublicRegistrationsList.tsx
closes #
Changes:
Screenshots:
=> feat: made it so that only users with public regs can see reg list

CHANGELOG.md, src/pages/Profile/components/ProfileSettings/index.tsx
closes #469 
Changes:
Screenshots:
=> feat: edit password

CHANGELOG.md, src/pages/EventDetails/components/EventRenderer.tsx
Fjernet boks som sa "Arrangementet gir ikke prikker om du..."
closes #677 
Screenshots:
=> refactor(event): fjernet boks om prikker

src/pages/Cheatsheet/index.tsx
Lagt til en bidragsknapp på kokeboksida der brukere blir videresendt til eposten sin, og det automatisk opprettes en ny mail med en forhåndsinnfylt mal.
=> Added cheat sheet contribution button

CHANGELOG.md
November update 🏂
closes #
Changes:
Screenshots:
=> November update 🏂

public/.well-known/security.txt
Legger til en (ny)standard fil som forteller folk hvor de kan kontakte oss hvis de finner sikkerhetsfeil på nettsiden
closes #
Changes:
Screenshots:
=> Added standard security.txt file

src/components/miscellaneous/TihldeLogo.tsx, src/pages/Landing/components/Wave.tsx
Jubileum
closes #
Changes:
Screenshots:
=> feat(jubileum): la til nedtelling

public/.well-known/security.txt, src/pages/Companies/components/CompaniesForm.tsx, src/pages/Companies/index.tsx
Oppdatering fra NOK
closes #
Changes:
Screenshots:
=> feat(companies): added "bedriftsekskursjon"

CHANGELOG.md, src/pages/EventDetails/components/EventRenderer.tsx
closes #742 
Changes:
Screenshots:
=> Arrangement knapp disables

CHANGELOG.md, src/AppRoutes.tsx, src/pages/Badges/get/index.tsx
Gjør det mulig å erverve en badge gjennom en lenke
closes #
Changes:
Screenshots:
=> feat(badge): badges kan erverves gjennom en lenke

src/pages/Badges/components/BadgeCategoryItem.tsx
listen med kategorier renders dårlig i safari på mobil tihlde.org/badges/kategorier/
closes #
Changes:
Screenshots:
=> fix(): badge list style

src/pages/Landing/components/Wave.tsx
closes #
Changes:
Screenshots:
- [ no visual change] The PR includes a picture showing visual changes
- [ no] Added Analytics-events if relevant
- [ no/refactor] CHANGELOG.md has been updated. [Guide](https://tihlde.slab.com/posts/changelog-z8hybjom)
=> added target=_blank to jubileums anchor button on landing page

CHANGELOG.md, src/pages/Profile/components/ProfileSettings/UserSettings.tsx
closes #
Changes:
Screenshots:
=> fixed link in user settings pointing to wiki

src/hooks/User.tsx
Frontend tolker nå write_all permission i lik grad med write permission på en modell
closes #
Changes:
Screenshots:
=> fix(permission): include write_all permission

CHANGELOG.md, package.json, src/index.tsx, yarn.lock
added vercel anaytics 
closes #
Changes:
Screenshots:
=> feat(analytics): added vercel analytics

CHANGELOG.md, package.json, src/hooks/User.tsx, src/index.tsx, src/pages/Landing/components/Wave.tsx, src/pages/Profile/components/ProfileSettings/UserSettings.tsx, src/pages/ShortLinks/index.tsx, yarn.lock
closes #
Changes:
Screenshots:
=> March update 

CHANGELOG.md, src/pages/Landing/components/EventsCalendarView.tsx
closes #
Changes:
Screenshots:
=> fix(calendar): fetch all events in calendar month

src/pages/Landing/components/Wave.tsx
closes #
Changes:
Screenshots:
=> fix(jub): remove jub button

src/constant.tsx, src/pages/Landing/components/NewStudentBox.tsx, src/pages/NewStudent/index.tsx
Endrer når ny-student boksen vises. Dette medførte at jeg måtte endre litt andre ting også.
closes #
Changes:
Screenshots:
=> ref(): change when new student box shows up

CHANGELOG.md, src/constant.tsx, src/pages/Landing/components/NewStudentBox.tsx, src/pages/NewStudent/index.tsx, yarn.lock
closes #
Changes:
Screenshots:
=> Dev to master

src/pages/Landing/components/NewStudentBox.tsx
closes #
Changes:
Screenshots:
=> fix(): new student box

CHANGELOG.md, src/pages/Groups/events/index.tsx
closes #802
Changes:
Screenshots:
=> fix: show event creation button to admins

src/hooks/Utils.tsx, src/pages/EventAdministration/components/EventEditor.tsx, src/pages/EventDetails/components/EventRenderer.tsx, src/types/Event.tsx
closes #
Changes: This PR changes the Event Editor such that the groups have the ability to add a contact person that is displayed in the Event Renderer.
Screenshots:
=> Feat(event)/contact person

src/pages/EventDetails/components/EventRenderer.tsx
∞ mulige deltagere
closes #
Changes:
Screenshots:
=> chore: infinite limit

src/pages/EventAdministration/components/EventEditor.tsx, src/pages/EventDetails/components/CountdownTimer.tsx, src/pages/EventDetails/components/EventRenderer.tsx, vite.config.ts
closes #
Changes:
Screenshots:
=> fix: not pay required

src/components/miscellaneous/TihldeLogo.tsx, src/components/navigation/Topbar.tsx, src/pages/Landing/components/Wave.tsx
Use normal logo
closes #863
Changes:
Screenshots:
=> chore: use normal tihlde LOGO

CHANGELOG.md, src/pages/EventAdministration/components/EventEditor.tsx, src/pages/EventDetails/components/EventRenderer.tsx
Changed display of contact person on event to full name, instead of id. Now it is the same as news.
closes #
Changes:
Screenshots:
=> changed display of contact person to full name instead of id

CHANGELOG.md, package.json, pnpm-lock.yaml, src/components/miscellaneous/AspectRatioImg.tsx, src/components/miscellaneous/JobPostListItem.tsx, src/components/miscellaneous/MarkdownRenderer.tsx, src/pages/EventAdministration/components/EventEditor.tsx, src/pages/EventDetails/components/EventRenderer.tsx, src/pages/JobPosts/index.tsx
closes #
Changes:
Screenshots:
=> 25. sep update ✨

src/components/miscellaneous/InfoBanner/InfoBannerAdmin.tsx, src/types/Misc.tsx
closes #
Changes:
Screenshots:
=> chore: fix banners

CHANGELOG.md, src/pages/Landing/components/EventsCalendarPopover.tsx
closes #
Changes:
Gjør pop-up komponenten mer oversiktlig. Legger til tittel + viser kun infromasjon som er relevant for arrangementet. Hvor mange som er på venteliste vises kun hvis det er en venteliste. etc
Screenshots:
=> chore: cleanup calendar pup-up

package.json, pnpm-lock.yaml, src/pages/Cheatsheet/components/Files.tsx, src/pages/Landing/components/Wave.tsx
Update packages. Update to newer vite version
closes #
Changes:
Screenshots:
=> vite 5.0.0 update

src/hooks/User.tsx, src/pages/Profile/components/ProfileEvents.tsx
Featur to filter expired events on profile page
closes #
Changes:
Screenshots:
=> added buttuns for filtering

src/pages/Events/components/EventsDefaultView.tsx, src/pages/Landing/components/EventsView.tsx
Changed API requests to fit new backend for filtering activitites
closes #
Changes:
Screenshots:
=> fixed filtering of events and activities

src/pages/EventAdministration/components/EventParticipants.tsx
Copy of participiants list of an event will now contain ids
closes #
Changes:
Screenshots:
=> added id for each user in copy of participants of an event

src/pages/Companies/index.tsx
closes #
Changes:
Screenshots:
=> changed text

src/pages/Profile/components/ProfileStrikes.tsx
closes #
Changes:
Screenshots:
=> changed email for strike message

package.json, pnpm-lock.yaml, src/components/miscellaneous/MarkdownRenderer.tsx
closes #
Changes:
Screenshots:
=> added package for allowing iframe

src/components/miscellaneous/reactions/EmojiShowcase.tsx
closes #
Changes:
Screenshots:
=> reduced number of showcase to two for mobile fit

src/pages/SignUp/index.tsx
Email on sign up has now a helpertext that explains the user to use an email the check often.
closes #
Changes:
Screenshots:
=> added helpertext

src/pages/EventAdministration/components/EventEditor.tsx
Removed timepicker from Event editor and set constant time limit to two hours.
=> removed timepicker. Paytime is set to constant 2 hours

src/components/miscellaneous/reactions/ReactionListItem.tsx
Made it so you can click the user paper component in reactions list - and it takes you to the user's profile, in the same way you can press "Se deltakere" and click on the person and go to their profile.  
closes #
Changes:
Screenshots:
=> Clickable user component in reactions list

src/pages/EventAdministration/components/Participant.tsx
waiting list number will only be rendered if not null
=> waiting list info will now only be rendered if not null

src/assets/css/index.css, src/components/inputs/Upload.tsx, src/components/miscellaneous/InfoBanner/InfoBannerAdminItem.tsx, src/pages/EventAdministration/components/EventEditPriorityPools.tsx, src/pages/EventAdministration/components/EventEditor.tsx, src/pages/EventAdministration/components/Participant.tsx, src/pages/GalleryDetails/components/GalleryEditor.tsx, src/pages/Groups/components/GroupAdmin.tsx, src/pages/Groups/fines/AddFineDialog.tsx, src/pages/NewsAdministration/components/NewsEditor.tsx, src/pages/Profile/components/ProfileAdmin.tsx, tailwind.config.ts
This will fix small issues with shadcn config and change buttons
closes #
Changes:
Screenshots:
=> Shadcn button refdesign

package.json, pnpm-lock.yaml, src/components/inputs/Upload.tsx, src/components/miscellaneous/InfoBanner/InfoBannerAdminItem.tsx, src/components/navigation/Footer.tsx, src/components/ui/separator.tsx, src/pages/EventAdministration/components/EventEditor.tsx, src/pages/GalleryDetails/components/GalleryEditor.tsx, src/pages/Groups/components/GroupAdmin.tsx, src/pages/NewsAdministration/components/NewsEditor.tsx
This pr will redesign the footer of the website
closes #
Changes:
Screenshots:
=> Shadcn redesign footer

src/components/miscellaneous/Linkify.tsx, src/components/miscellaneous/MarkdownRenderer.tsx
Fix bug of markdown and started on tailwindcss redesign
closes #
Changes:
Screenshots:
=> Refactor(shadcn)/markdown

src/pages/Landing/components/EventsCalendarPopover.tsx
Added underline and color for link i popover on event calander
closes #
Changes:
Screenshots:
=> fixed link for event calender

package.json, pnpm-lock.yaml, src/components/navigation/ProfileTopbarButton.tsx, src/components/ui/avatar.tsx, src/components/ui/separator.tsx, src/pages/Badges/BadgesLeaderboard.tsx, src/pages/Badges/details/index.tsx, src/pages/EventAdministration/components/Participant.tsx, src/pages/EventDetails/components/EventPublicRegistrationsList.tsx, src/pages/Groups/about/MembersCard.tsx, src/pages/Groups/about/MembershipHistoryListItem.tsx, src/pages/Groups/about/MembershipListItem.tsx, src/pages/Groups/fines/UserFineItem.tsx, src/pages/Profile/index.tsx, src/pages/StrikeAdmin/components/UserStrikeListItem.tsx, src/pages/UserAdmin/components/PersonListItem.tsx
Change avatars to shadcn avatars
closes #
Changes:
Screenshots:
=> redesigned to shadcn avatars

CHANGELOG.md, package.json, pnpm-lock.yaml, src/components/miscellaneous/ThemeSettings.tsx, src/components/navigation/ProfileTopbarButton.tsx, src/components/ui/dropdown-menu.tsx
changed themesettings component to shadcn
closes #
Changes:
Screenshots:
=> changed themesettings component to shadcn

src/components/miscellaneous/MarkdownRenderer.tsx
closes #
Changes:
Screenshots:
=> fixed seperator for markdown

CHANGELOG.md, package.json, pnpm-lock.yaml, src/assets/css/index.css, src/components/miscellaneous/DetailContent.tsx, src/components/miscellaneous/LoadingSpinner.tsx, src/components/miscellaneous/QRButton.tsx, src/components/miscellaneous/ShareButton.tsx, src/components/miscellaneous/UserInformation.tsx, src/components/ui/alert.tsx, src/components/ui/checkbox.tsx, src/components/ui/collapsible.tsx, src/components/ui/expandable.tsx, src/pages/EventDetails/components/CountdownTimer.tsx, src/pages/EventDetails/components/EventPriorityPools.tsx, src/pages/EventDetails/components/EventRenderer.tsx, src/pages/Groups/forms/index.tsx, src/pages/JobPostDetails/components/JobPostRenderer.tsx, src/pages/Profile/components/ProfileEvents.tsx, src/pages/Profile/index.tsx, src/pages/Wiki/index.tsx, tailwind.config.ts
closes #
Changes:
Screenshots:
=> Refactor event renderer

src/components/miscellaneous/UpdatedAgo.tsx, src/components/miscellaneous/reactions/EmojiPickHandler.tsx, src/components/miscellaneous/reactions/EmojiShowAll.tsx, src/components/miscellaneous/reactions/ReactionHandler.tsx, src/pages/EventDetails/components/EventRenderer.tsx, src/pages/NewsDetails/components/NewsRenderer.tsx
closes #
Changes:
Screenshots:
=> refactored news renderer

src/components/inputs/MarkdownEditor.tsx
closes #
Changes:
Screenshots:
=> added description of how to use spaces

src/components/miscellaneous/ShareButton.tsx, src/components/ui/button.tsx, src/pages/EventDetails/components/EventRenderer.tsx, src/pages/NewsDetails/components/NewsRenderer.tsx
closes #
Changes:
Screenshots:
=> changed position of share and edit button for event

src/components/navigation/ProfileTopbarButton.tsx, src/hooks/Theme.tsx
closes #
Changes:
Screenshots:
=> diasbled theme selector

src/pages/Profile/components/ProfileStrikes.tsx
closes #
Changes:
Screenshots:
=> changed info for contact for strikes

CHANGELOG.md, src/pages/EventDetails/components/EventRenderer.tsx
This PR removes the unregister button on an event if the user has paid for the registration
closes #
Changes:
Screenshots:
=> removed unregister button if registration is paid

CHANGELOG.md, src/components/miscellaneous/EventListItem.tsx, src/components/miscellaneous/MarkdownRenderer.tsx, src/pages/Landing/components/EventsCalendarView.tsx, src/pages/Landing/components/EventsListView.tsx, src/types/Enums.tsx, src/types/Event.tsx
This PR will sort events by category
closes #
Changes:
Screenshots:
=> sort after category

src/pages/EventDetails/components/EventRenderer.tsx
closes #
Changes:
Screenshots:
=> fixed category for event view

.github/workflows/nodejs.yml, pnpm-lock.yaml, src/components/miscellaneous/AspectRatioImg.tsx, src/components/miscellaneous/EventListItem.tsx, src/components/navigation/Page.tsx, src/components/navigation/ProfileTopbarButton.tsx, src/components/navigation/ScrollToTop.tsx, src/index.tsx, src/pages/EventAdministration/components/EventEditor.tsx, src/pages/ForgotPassword/index.tsx, src/pages/Landing/components/NewStudentBox.tsx, src/pages/Landing/components/Story.tsx, src/pages/LogIn/index.tsx, src/pages/NewStudent/index.tsx, src/pages/SignUp/index.tsx, src/utils.tsx
closes #
Changes:
Screenshots:
=> fixed small design bugs  and added scrollToTop component

src/components/ui/expandable.tsx
closes #1042 
Changes:
* Pass p-4 to children in Expandable to fix opening/closing stutter
Screenshots:
=> Fix accordion stutter

CHANGELOG.md, package.json, pnpm-lock.yaml, src/components/navigation/ProfileTopbarButton.tsx, src/components/navigation/TopbarNotifications.tsx, src/pages/Groups/overview/GroupItem.tsx, src/pages/NewStudent/index.tsx
Redesign of Ny Student page.
closes #
Changes:
Screenshots:
=> Redesing of Ny student page

src/pages/SignUpOptions/index.tsx
closes #
Changes:
Screenshots:
=> Added info box about how to create a feide user

src/components/miscellaneous/ThemeSettings.tsx, src/components/navigation/ProfileTopbarButton.tsx, src/components/navigation/TopbarNotifications.tsx
closes #
Changes:
Screenshots:
=> Redesign of notifications

src/pages/Profile/components/ProfileSettings/UserSettings.tsx, src/pages/SignUp/index.tsx
closes #
Changes:
Screenshots:
=> fixed error on updating user, and form errors on manual singup

src/AppRoutes.tsx, src/URLS.tsx, src/components/forms/FieldView.tsx, src/components/navigation/Navigation.tsx, src/components/ui/card.tsx, src/components/ui/expandable.tsx, src/hooks/Group.tsx, src/pages/Admissions/components/GroupAdmission.tsx, src/pages/Admissions/index.tsx, src/pages/Form/index.tsx, src/pages/NewStudent/index.tsx
closes #
Changes:
Screenshots:
=> Overview of admissions for groups in TIHLDE

src/components/forms/FieldView.tsx, src/components/inputs/Textarea.tsx, src/pages/Admissions/components/GroupAdmission.tsx, src/pages/Admissions/index.tsx
closes #
Changes:
Screenshots:
=> Small fixes on UI for admissions

src/AppRoutes.tsx, src/pages/Groups/GroupDetails.tsx, src/pages/Groups/components/GroupAdmin.tsx, src/types/Enums.tsx
closes #
Changes:
Screenshots:
=> Fix permission for committee leaders for creating group form

src/components/forms/FormAnswers.tsx, src/components/ui/card.tsx
closes #
Changes:
Screenshots:
=> added extra fields for submission

CHANGELOG.md, pnpm-lock.yaml, src/pages/EventAdministration/components/Participant.tsx
Added allergies to the event participants list
Screenshots:
=> Added allergies

CHANGELOG.md, src/components/navigation/Footer.tsx, src/pages/Profile/components/ProfileSettings/NotificationSettings.tsx, src/pages/Profile/components/ProfileSettings/index.tsx
closes #
Changes:
Screenshots:
=> added discord invite link to footer and profile

CHANGELOG.md, package.json, pnpm-lock.yaml, src/components/inputs/Textarea.tsx, src/components/navigation/Footer.tsx, src/pages/Badges/details/index.tsx, src/pages/Profile/components/BioEditor/BioEditor.tsx, src/pages/Profile/components/ProfileSettings/NotificationSettings.tsx, src/pages/Profile/components/ProfileSettings/index.tsx, src/pages/Profile/index.tsx
closes padding issue. 
Changes:
moved the content into the <CardContent> component
Note: something is wrong, so my pull request includes the Mid September update. Talked to Mads about it, and he said that he knows of the issue and is trying to fix it.
=> Fixed the padding issue from frikk

CHANGELOG.md, index.html, src/pages/Badges/details/index.tsx
closes #
Changes:
Screenshots:
=> added meta settings for reverting zoom on inputs

src/pages/EventDetails/components/EventRenderer.tsx
=> Changed the on-cancel warning to more percise.

src/pages/Badges/BadgesLeaderboard.tsx
closes #1093  
Changes: removed flex from container to stack cards correctly
=> fixed overflow issue on badges leaderboard

src/components/forms/FormDetailsEditor.tsx, src/pages/EventAdministration/components/EventEditor.tsx, src/pages/Form/index.tsx, src/types/Form.tsx
This PR will add the option to add a description for a group form. The description will be shown for the users that are answering the form.
=> Group Form description

src/pages/UserAdmin/components/UserFilter.tsx
closes #1082 
Changes:
Debounce logic for form inputs.
=> Fixed the re-rendering of UserFilter on admin page every 500ms

src/pages/Profile/components/ProfileEvents.tsx, src/pages/Profile/index.tsx
Fixed icon issue and turncated overflowed text
closes #1116 
Changes:
Icons wont shrink on smaller screens, and overflowed text will truncate if overflowed.
Screenshots:
=> Fixed icon issue and turncated overflowed text

src/pages/EventAdministration/components/Participant.tsx, src/pages/EventDetails/components/EventRenderer.tsx
Admins for an event can now see if the participants have paid for the event
=> Info about payment orders

src/pages/EventAdministration/components/EventParticipants.tsx
Deleted lines that caused the crash. They caused an infinite loop. 
closes #
Changes:
Screenshots:
=> Deleted unnecessary lines that caused the crash

tailwind.config.ts
Fix bug where there was extra quotation marks around the borderradius that removed all border radiuses.
closes #
Changes:
Fix border bug
Screenshots:
=> Remove extra quotationmarks in tailwind config

src/components/miscellaneous/MarkdownRenderer.tsx
=> Fix(markdown)/renderer

CHANGELOG.md, package.json, pnpm-lock.yaml, src/pages/Landing/components/EventsCalendarPopover.tsx, src/pages/Landing/components/EventsCalendarView.tsx, src/pages/Landing/components/EventsCalendarViewBase.tsx
- **Replaced material-ui calendar with shad/cn**
- **Fixed calendar components**
- **Updated README**
closes #1169
Changes:
Removed the old calendar dependency
Added ShadCN-based calendar component
Added skeleton loading to calendar event popover
Screenshots:
=> REFACTOR: Update events calendar widget to ShadCN

src/pages/Profile/components/ProfileSettings/UserSettings.tsx
closes #
Changes:
Screenshots:
=> Users can now update their pb

CHANGELOG.md, pnpm-lock.yaml, src/components/navigation/ProfileTopbarButton.tsx
Multiple users has complained about the feedback tutorial keeps showing up after the initial popup.
closes:
Changes:
Changed from a cookie solution (which will expire, once the cookie expires) to a localStorage based solution
Screenshots:
=> FIX: Feedback/bug popup wont stop appearing

src/components/navigation/Footer.tsx
closes #
Changes:
Screenshots:
=> fixed link taking you to a non existing page

CHANGELOG.md, src/pages/Landing/components/EventsCalendarViewBase.tsx
- **Replaced material-ui calendar with shad/cn**
- **Fixed calendar components**
- **Updated README**
- **Added back color codes and increased contrast**
- **Linting**
- **Fixed calendar scroll bar**
closes #1210
Changes:
Replaced calendar cell div with ScrollArea from ShadCN
Screenshots:
=> Fix scrollbar in events calendar

src/api/api.tsx, src/components/forms/FormAnswers.tsx, src/components/inputs/Upload.tsx, src/components/miscellaneous/MarkdownRenderer.tsx, src/hooks/Feedback.tsx, src/pages/Feedback/index.tsx, src/pages/Landing/components/EventsCalendarViewBase.tsx, src/pages/NewGroupAdministration/index.tsx, src/pages/Profile/components/ProfileSettings/UserSettings.tsx, src/pages/SignUp/index.tsx, src/pages/Wiki/index.tsx
Fixed all the dummy typescript and eslint mistakes over the years
Changes:
All lint errors gone
Screenshots:
=> chore: Fixed all eslint linting errors

CHANGELOG.md, src/pages/Landing/components/EventsCalendarView.tsx
closes:
Changes:
spreads the filter in the useEvent hook ;)
Screenshots:
=> Date filter didnt apply correctly in event calendar

src/api/auth.ts, src/components/miscellaneous/InfoBanner/InfoBannerAdmin.tsx, src/components/miscellaneous/shortCutMenu/Item.tsx, src/components/miscellaneous/shortCutMenu/Logout.tsx, src/components/miscellaneous/shortCutMenu/index.tsx, src/components/navigation/BottomBar.tsx, src/components/navigation/Navigation.tsx, src/components/navigation/ProfileTopbarButton.tsx, src/components/navigation/Topbar.tsx, src/hooks/User.tsx, src/hooks/Utils.tsx, src/hooks/auth.ts, src/pages/Badges/category/CategoryBadgesList.tsx, src/pages/Badges/category/index.tsx, src/pages/Cheatsheet/index.tsx, src/pages/EventDetails/index.tsx, src/pages/EventRegistration/index.tsx, src/pages/Groups/forms/index.tsx, src/pages/Landing/index.tsx, src/pages/LogIn/index.tsx, src/pages/MainLayout.tsx, src/pages/Profile/index.tsx, src/pages/Wiki/components/WikiNavigator.tsx, src/pages/Wiki/index.old.tsx, src/root.tsx, src/routes.ts, src/utils.tsx
Changes:
Fixed som auth endpoints and updated auth hook for working on localhost between dev and prod.
Some cleanup of code that didn't make any sense and sections that wasn't detected by eslint
=> CHORE: Code cleanup and fixed borked endpoints

src/components/miscellaneous/JobPostListItem.tsx, src/pages/Companies/index.tsx, src/pages/Events/components/ActivitiesDefaultView.tsx, src/pages/Events/components/EventsDefaultView.tsx, src/pages/Events/index.tsx, src/pages/JobPosts/index.tsx, src/pages/News/index.tsx
Changes:
Changes the design of filter forms in both events page and job announcements
Screenshots:
=> Feat(filters)/unified design for job and events filter

package.json, pnpm-lock.yaml, src/root.tsx
* feat: add posthog-js
* feat: fix posthog-js
closes #
Changes:
Screenshots:
=> POSTHOG Update
