- src/components/miscellaneous/Avatar.tsx
- src/containers/EventAdministration/components/Participant.tsx
- src/containers/UserAdmin/components/PersonListItem.tsx
Viser nå brukerens avatar i deltakerliste og useradmin, se screens
closes #11 
> refactor(user-avatar): display avatar in participant and useradmin

- CHANGELOG.md
- src/api/hooks/User.tsx
- All cache on page is reset when a user logs out or in
closes #80 
> fix(cache): remove on authing

- CHANGELOG.md
- src/containers/Profile/components/ProfileSettings.tsx
- src/containers/UserAdmin/components/PersonListItem.tsx
- HS and Index can now edit users in user-admin through an extended version of the profile-settings form.
closes #83 
> feat(users): allow edit of users in useradmin

- CHANGELOG.md
- src/api/api.tsx
- src/api/hooks/Event.tsx
- src/containers/EventAdministration/components/EventMessageSender.tsx
- src/containers/EventAdministration/components/EventParticipants.tsx
closes tihlde/Lepton#169
Changes:
Admins på arrangementer kan sende epost/varsel til de påmeldte på et arrangement.
Screenshots:
> feat(event): send message to registered users at event

- CHANGELOG.md
- src/pages/Profile/components/ProfileSettings.tsx
closes #160 
Changes:
Legger til hjelpertekst i brukerprofil under allergier
Screenshots:
> feat(profile): adding helper text allergies

- src/components/forms/FormAnswers.tsx
- src/components/forms/FormView.tsx
- src/hooks/Form.tsx
- src/pages/EventDetails/components/EventRegistration.tsx
- src/pages/Form/index.tsx
closes # N/A
Changes:
Fixes an issue where you couldn't submit a form with no fields, resulting in that you weren't able to sign up for new events if there was an unanswered evaluationform with no fields blocking. Also added better text feedback to users and fixed a bug in the table with form-answers pagination counts.
> fix(forms): allow submit when no fields

- .github/workflows/changelogger.yml
closes #
Changes:
Stops issue where it's created a new PR to update the changelog when the first pr to update the changelog is merged into dev.
Screenshots:
> fix(changelogger): no new pr on branch update

- CHANGELOG.md
- src/components/forms/FormAnswers.tsx
closes #164 
Changes: Legger til knapp for å kunne laste ned svar på arrangementer som en csv fil.
Screenshots:
> feat(eventadmin): add button to download event-answers as csv

- CHANGELOG.md
- src/pages/Pages/specials/Index/index.tsx
closes #15 
Changes: Legger til tegnforklaringer på om index siden. 
Jeg vurderte å bruke infoCard komponenten, men jeg følte at det ga inntrykket av at all informasjonen var like viktig på siden, ettersom hele siden bruker infoCard komponenter til å vise informasjon.
Screenshots:
> feat(changelog):adding captions on om index page

- src/components/forms/FormAnswers.tsx
closes #
Changes:
Fikk filnavn uten `.csv` på både windows og linux. Denne "hacky" løsningen funker derimot
Screenshots:
> fix(csv): fixes the filename of csv downloads

- src/index.tsx
Users now get a "Rickrolled"-badge when they type `badge()` into the console.
Added the badge to both the prod and dev-api with the same id, so it works both places.
Changes:
Screenshots:
> feat(badges): add rickrolled badge

- CHANGELOG.md
- src/pages/Cheatsheet/index.tsx
Viser en helt falsk teller på antall andre som koker akkurat nå. Tar hensyn til tidspunkt på dagen og om det er helg eller ukedag.  Antallet oppdateres hvert 20 sekund. Også byttet ut makeStyles med styled på siden.
closes #270 
Changes:
Screenshots:
> feat(cheatsheet): add live cheating count

- CHANGELOG.md
- src/components/navigation/TopbarNotifications.tsx
- src/hooks/Notification.tsx
- src/hooks/Utils.tsx
- src/pages/EventDetails/components/EventPriorities.tsx
- src/pages/EventDetails/components/EventRenderer.tsx
- src/utils.tsx
closes #220 
Changes:
- Påmeldingsknapp teller ned til påmeldingsstart og bytter til "Meld på" automatisk
- Brukere kan se om de er prioritert på et arrangement ved at klassen/studiet er uthevet og det er en tooltip over den ved hovring
- Laster nå inn varsler først når boksen åpnes.
- Varsler oppdateres til read=true kun 1 gang nå, fremdeles når listen over varsler lukkes.
- Fikset feil der en ekstra snackbar ble vist ved deling i nettlesere som ikke støtter ShareAPI
- Refaktorert litt styling
Screenshots:
> feat(events): countdown to registration and prioritized indicator

- CHANGELOG.md
- src/components/story/Story.tsx
Viser annonser markert med fortløpende opptak med "Fortløpende opptak" og ikke dato annonsen går ut.
closes #312
Changes:
Screenshots:
> feat(stories): shows continuously hiring in stories

- CHANGELOG.md
- src/components/layout/SidebarList.tsx
- src/pages/EventAdministration/components/EventEditor.tsx
- src/pages/EventAdministration/index.tsx
- src/types/Event.tsx
Viser at et arrangement er stengt i eventadmin. Dette vises både i sidepanelet med ett icon og på selve arrangementet i adminpanelet. Denne ble laget i sammenheng med denne pull requesten fra backend https://github.com/TIHLDE/Lepton/pull/401. (Det går hent fint å kjøre denne uten oppdateringen fra backend, men da vises ikke iconet i sidepanelet.)
Ved å vise et klart icon i sidepanelet kan adminbrukere tydelig se hvilke arrangementer som er stengt uten å klikke på dem. 
closes #313
Changes:
Screenshots:
> Fix(eventadmin):show that event is closed in eventadmin

- CHANGELOG.md
- src/components/inputs/Upload.tsx
- src/pages/EventAdministration/components/EventEditor.tsx
- src/pages/EventAdministration/components/EventFormAdmin.tsx
- src/pages/JobPostAdministration/components/JobPostEditor.tsx
- src/pages/NewsAdministration/components/NewsEditor.tsx
- src/pages/Profile/components/ProfileSettings.tsx
Viser brukeren hva som er foretrukket størrelsesforhold på et bilde når de laster det opp.
closes #338 
Changes:
Screenshots:
> feat(image-upload): showing preferred image ratio

- CHANGELOG.md
- src/pages/NewsAdministration/components/NewsEditor.tsx
- src/types/News.tsx
Nå er det mulig å endre og opprette nyheter uten forfatter
closes #445
Changes:
Screenshots:
> fix(news): not all news needs a creator

- CHANGELOG.md
- src/pages/Groups/fines/FineItem.tsx
- src/pages/Groups/fines/index.tsx
Made the buttons in the Fine elements say what the button does. Previously the state of the fine has been displayed.
Screenshots:
> fix(fines): Made button action more intuitive

- src/pages/EventDetails/components/EventRenderer.tsx
closes #507
Changes: removed favorite button in preview
Screenshots:
> fix(bug): remove favorites in preview

- CHANGELOG.md
- src/pages/Groups/fines/AddFineDialog.tsx
- src/pages/Groups/fines/FineItem.tsx
- src/types/Group.tsx
https://github.com/TIHLDE/Lepton/pull/554
closes N/A
Changes:
- Brukere kan legge til bilde som bevis på bøter
Screenshots:
> feat(fines): add image

- CHANGELOG.md
- src/pages/EventDetails/components/EventRenderer.tsx
Under arrangement er det påmeldingsfrist. Her sto det opprinnelig "Slutt:" med dato etterfulgt. Dette har blitt endret til "Stenger:"
closes #572 
Changes:  Endret påmeldingsfrist-tekst fra slutt til stenger
Screenshots: 
> endret påmeldingsfrist tekst fra slutt til stenger

- CHANGELOG.md
- src/pages/Landing/components/EventsCalendarView.tsx
Fixed the size of events in the calendar for mobile
closes #697 
Changes:
Screenshots:
> fix(bug): fixed calendar size for mobile

- CHANGELOG.md
- src/pages/JobPostDetails/components/JobPostRenderer.tsx
closes #711 
Changes: Logoen til bedrifter som har utlyst stillinger ble dyttet nederst på siden. Nå er denne flyttet øverst.
Screenshots:
- [ x] The PR includes a picture showing visual changes
- [x ] CHANGELOG.md has been updated. [Guide](https://tihlde.slab.com/posts/changelog-z8hybjom)
> feat(JobPostRendering):move-logo-up

- src/pages/EventAdministration/components/EventParticipants.tsx
- src/pages/EventAdministration/components/Participant.tsx
waiting list will now be properly ordered according to their respective waiting list number. also added a field to see this number for admins. 
Changes:
Screenshots:
> Fix(waiting list)/fix waiting list order

- src/pages/EventAdministration/components/EventParticipants.tsx
closes #
Changes:
waiting list will now only do sorting when the event has priority pool. this was needed because the sorting takes some time (issue for the future to make this quicker), and on events that are without priority pools, the ordering is not needed.
Screenshots:
> waiting-list will now only be sorted if there is a priority pool

- src/components/navigation/Topbar.tsx
- src/pages/ForgotPassword/index.tsx
- src/pages/LogIn/index.tsx
- src/pages/SignUp/index.tsx
This will remove MUI from signin, signup and forgot password pages, and use shadcn
closes #
Changes:
Screenshots:
> Remove MUI from signin pages

- CHANGELOG.md
- src/AppRoutes.tsx
- src/URLS.tsx
- src/components/miscellaneous/MarkdownRenderer.tsx
- src/components/navigation/Navigation.tsx
- src/components/navigation/Topbar.tsx
- src/pages/Changelog/index.tsx
- src/pages/Wiki/specials/Index/ChangelogCard.tsx
- src/pages/Wiki/specials/Index/index.tsx
- **Added navbar destination for changelog**
- **Export changelog URLs to use in changelog page**
- **Add classname prop to used components**
- **Created page and added routing destination**
Changes:
Added a page for viewing changelogs for Kvark and Lepton
The route is currently not protected by auth (changelog exists in repos and is public anyways)
Screenshots:
> feat(changelog)/changelog site for logged in users

- src/pages/GalleryDetails/index.tsx
Added space between description and action buttons. Moved buttons to be in line with title.
closes #1113
Changes: 
Fixed the space between title, description and buttons on all types of screens. 
Screenshots: 
> Refactor(gallery)/fix description width

- CHANGELOG.md
- src/pages/GalleryDetails/components/GalleryRenderer.tsx
Fixed position of load more button in galleri 
closes #1111 
Changes: 
Placed button outside picture div, and centered it below the pictures. Can't test in localhost because there is no pictures in galleri. We tested with local pictures and the button was placed correctly. 
Screenshots:
> Refactor(gallery)/move pagination button below pictures

- src/pages/Groups/laws/AddLawDialog.tsx
- src/pages/Groups/laws/LawItem.tsx
- src/utils.tsx
When writing a subparagraph law, if the number after the period is single digit, add a zero *before* the digit and not after.
For example:
- "3" -> 3
- "3.1" -> 3.01
- "3.12" -> 3.12
closes #1180
Changes:
Parse paragraph numbers by prefixing a zero digit to a single digit decimal number
Screenshots:
> Parse paragraph numbers by prefixing a zero digit to a single digit decimal number

- src/pages/EventAdministration/components/Participant.tsx
Added allergies on event-participant list, only showing allergies on users with allergies.
This user is allergic to good grades.
closes #
Changes:
Screenshots:
> Added allergies on event-participant list,

- CHANGELOG.md
- src/components/navigation/Topbar.tsx
closes `none`
Changes:
Replaces the scroll state with a simple boolean state isOver.
This reduces react re-renders from re-rendering on each scroll step, to only re-render once the trigger is reached.
I also took the time to remove the useMediaQuery (why do we have this) hook and replaced it with native CSS.
Screenshots:
**React-Scan visualization before**
https://github.com/user-attachments/assets/254f3cbe-542e-428e-b8c7-5e17c2e32caf
**React-Scan visualization after**
https://github.com/user-attachments/assets/d0a04cd9-c120-42c2-9b09-180618e905fd
**Responsive design with CSS media-queries**
https://github.com/user-attachments/assets/19324ced-2b6a-4453-b540-3e4d11b84fe2
> Performance fix for topbar component

- CHANGELOG.md
- src/pages/EventAdministration/components/Participant.tsx
closes #1205 
Changes:
* Fixes an overflow issue that occures when event participants have a long list of allergies. 
* Prevents checkbox from shrinking when participants have a long list of allergies
Screenshots:
Before:
After:
> improve layout for allergy information

- CHANGELOG.md
- src/pages/Groups/about/MembershipListItem.tsx
Allergies is a very personal. It shouldn't be shown to those that doesn't need to.
closes:
Changes:
Added conditional rendering depending if you have write permissions to the group.
This does not change the backend in any way. (didn't want to do any potential breaking changes).
NOTES:
The isAdmin param should probably be renamed to hasWritePermission.
> FIX: Removed allergy from group lists for those without permissions to write
